Remove japanese labels from the state mashine
Because the build is failed in GitBook. It has the following message:

```bash
phantom stdout: TypeError: 'undefined' is not an object (evaluating 'w[0]')

  file:///tmp/book/node_modules/gitbook-plugin-mermaid/convert/assets/mermaid.min.js:11
  file:///tmp/book/node_modules/gitbook-plugin-mermaid/convert/assets/mermaid.min.js:10
  file:///tmp/book/node_modules/gitbook-plugin-mermaid/convert/assets/mermaid.min.js:13
  file:///tmp/book/node_modules/gitbook-plugin-mermaid/convert/assets/mermaid.min.js:13
  file:///tmp/book/node_modules/gitbook-plugin-mermaid/convert/assets/mermaid.min.js:13
  file:///tmp/book/node_modules/gitbook-plugin-mermaid/convert/assets/mermaid.min.js:13
  file:///tmp/book/node_modules/gitbook-plugin-mermaid/convert/converter.html:34 in renderToSvg
  phantomjs://webpage.evaluate():2
  phantomjs://webpage.evaluate():3
  phantomjs://webpage.evaluate():3

Template render error: (/tmp/book/ja/developer/state_machine.md)
  TypeError: Cannot call method 'replace' of null (In file 'developer/state_machine.md')
```